# Generated by Django 5.0.7 on 2024-07-23 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='detailed_description',
            field=models.TextField(),
        ),
    ]
